//--base---

let citiesHY = ['Երևան','Աբովյան','Ալավերդին','Ախթալա','Այրում','Արմավիր','Արարատ','Արթիկ','Արտաշատ','Գավառ','Գյումրի','Գորիս','Եղեգնաձոր','Եղվարդ','Թալին','Իջևան','Ծովագյուղ','Կապան',
'Հրազդան','Մասիս','Մարտունին','Շորգակաթ','Չարենցավան','Պեմզաշեն','Սևան','Սպիտակ','Վաղարշապատ','Վանաձոր','Վեդի', 'Կանբերա', 'Ադելաիդա', 'Մելբուրն', 'Սիդնեյ',
'Լուանդա','Դիլի','Բրիջթաուն','Բելմոպան','Բելիզ','Թիմֆուն','Բույումբուրա','Ջորջթաուն','Գվատեմալա','Ադիս Աբեբա','Հարարե','Ասմեռա','Թունիս','Ջակարտա','Մադրիդ','Ալիկանտե','Ալկալա դե Էնարես',
'Ալկոբենդաս','Ալկորկոն','Ալմերիա','Արանխուես','Բարսելոնա','Բենիդորմ','Բենիկասիմ','Գուադալախարա','Գրանադա','Դենիա','Ինկա','Լա Պուեբլա','Լաս Ռոսաս դե Մադրիդ','Խերես դե լա Ֆրոնտերա','Կալա Ռաջադա',
'Կալպ','Կամպելյո','Կան Պիկաֆորտ','Կոսլադա','Կորդովա','Մալագան','Մախադաոնդա','Մանակոր','Մարբելյա','Պալմա','Պոսուելո դե Ալարկոն','Պորտ Ալկուդիա','Պորտ դե Պոլենսա','Պորտ դե Սոլեր','Սան Խուան դե Ալիկանտե',
'Սան Վիսենտե դել Ռասպեչ','Սևիլիա','Սինե','Վալենսիա','Վիլյախոյոսա','Տառագոնա',
'Թեհրան','Աստարա','Զահեդան','Զանջան','Թավրիզ','Կարաջ','Ղազվին','Մաշհադ','Մարաղա','Մյանեն','Շահրուդ','Ջուղա','Սեմնան',
'Ռիգա','Աինազի','Ալուկսեն','Բալվին','Բաուսկան','Գյուլբենե','Դագդա','Դոբելե','Թալսին','Ժելավա','Իմանալով','Լիմբազի','Լյուդա','Կուլդիգան','Կրտավա','Մադոնա','Յուրմալա','Պրիլի','Ջեքաբպիլս',
'Ռեզեկնան','Սալասպիլս','Սալդուս','Սահակաստի','Սիգուլդա','Վալկա','Վալմիերա','Վենտպիլս','Օլեյին',
'Մոնրովիա','Վիլնյուս','Կաունաս','Կլայպեդա','Ալյաս','Բիրզայ','Էլ','Կազլի Ռուդա','Կալվարիան','Սալինկինային',
'Պնոմպեն','Օտտավա','Էդմոնտոն','Կալգարի','Մոնրեալ','Վանկուվեր','Տորոնտո','Վիլլեմստադ','Մորոնին','Ավարիա','Սայանյան','Սեուլ','Բուսան','Բուդապեշտ','Դեբրեցեն','Սեգեդ','Սեքեշֆեհերար','Սոմբատհեյ',
'Անտանանարիվո','Արական','Մակաո','Պորտ Լուի','Աբու Դաբի','Ալ-Աին','Աջման','Դուբայ','Պալակիր','Քիշնև','Բելցին','Բասարաբեասկա','Բյուրունա','Գլոդանի','Դոնդուսենի','Դրոչիա','Եդինտ','Լիպկանի','Կահուլ','Կոզեին',
'Կոմատր','Կրիխովա','Կրիուլենի','Յալովենի','Նիսոֆենին','Չեդրիր Լունգան','Ռեզինան','Սենեգա','Սյունիքի','Սորոկա','Ստրասենի','Վադուլ-լուի-վոդա','Օտատին','Օրհի','Ֆալեշին',
'Աբուջա','Լագոս','Ալոֆի','Ստոկհոլմ','Աքերսբերգա','Գոտեմբուրգ','Էսլով','Էսկիլստունա','Թրլեբորգ','Լանդկոնա','Լունդ','Կատրինհոլմ','Հելսինգբորգ','Ձեռք բերելով','Մալմոն','Նիկոպինգ','Նորվեգինգ',
'Սալա','Վաստերաս','Տրոսա','Օստհամմար','Ֆլեն','Սանտիագո','Անտաֆագաստա','Արիքա','Թալքա','Լա Սերենան','Կազաբլանկան','Կոպիապո','Պուերտ Վիլյամս','Պուերտո Մոնտ','Պունտա Արենաս','Ռանչագուա','Վալդիվիա','Վալպարաիսոն',
'Լիմա','Աբանկայ','Անդալույաս','Արեկիպա','Աքորիա','Բագուա Գրանդե','Զունիգա','Իկիտոս','Իմպերիալ','Կալլա','Կախամարկա','Կուսկո','Հուաչոն','Հուարազ','Մարկիսկալ','Մոյոբամբա','Մոուգեգուա','Յաուլի',
'Նյուուո Իմպերիալ','Չանչայ','Չաչապոյաս','Չիչին Ալտա','Պաիտա','Պուերտո Մալդոնադո','Պունո','Ջուլիջա','Սալլա','Սան Լուիս դե Կանետե','Սան Վիսենտե դե Կանետե','Տալաա','Տակնան','Տինգո Մարիա','Քիլմանան','Օլոֆ Պալմե','Օրոպեսա',
'Մոսկվա','Սանկտ Պետերբուրգ','Նովոսիբիրսկ','Եկատերինբուրգ','Նիժնի Նովգորոդ','Աբազա','Աբական','Աբինսկ','Ագալաթովո','Ագինսկին','Ագրիզ','Ադիգեյսկ','Ազնակեևո','Ազով','Ալադինո','Ալաթիր',
'Բրատիսլավա','Կարակաս','Վալենսիա','Թբիլիսի','Սուխումի','Ախալքալաքի','Բաթումի','Բակուրիան','Բորժոմ','Գագրա','Գարդաբան','Գորի','Զեստափոն','Զուգդիդի','Լանչխութ','Խաշուր','Կասպ','Կոբուլեթին',
'Մառնեուլ','Մցխեթա','Նիկոսին','Նոր Աթոս','Ռուսթավի','Սադախլո','Սամտրեդիա','Սաչխերե','Սենակ','Սուրամ','Ցխինվալի','Փոթի','Քութաիսի','Օզուրգեթ','Անկարա','Ադանա','Անթալիա','Բուրսա','Իզմիր','Կեսարի','Ստամբուլ',
'Վիեննա','Ինսբրուկ','Լինց','Մինսկ','Գոմել','Վիտեբսկ','Սոֆիա','Բուրգաս','Դոբրիխ','Հասկովո','Պազարջիկ','Պեռնիկ','Պլևեն','Պլովդիվ','Ռուզե','Վառնա','Վրացա','Երուսաղեմ','Բիթ Շեսշ','Բնեյ Բրակ',
'Էին Բոկեկ','Էին Գեդին','Թել Ավիվ',
'Կիրյաթ Թիվան','Հայֆա','Յոկնեյմ Իլիտ','Նազարեթ','Նետանիա','Տիբերիա','Վարշավա'
]

let citiesENG =[
    "abu dhabi", "abuja", "accra", "addis ababa", "algiers", "amman", "amsterdam", "andorra la vella", "ankara", "antananarivo", "apia", "ashgabat", "asmara", "asuncion", "athens", "ararat", "armavir", "artashat", "abovyan", "alicante", "ankara", "adana", "antalya",
    "baghdad", "baku", "bamako", "bandar seri begawan", "bangkok", "bangui", "banjul", "basseterre", "beijing", "beirut", "belfast", "belgrade", "belmopan", "berlin", "bern", "bishkek", "bissau", "bogota", "brasilia", "bratislava", "brazzaville", "bridgetown", "brussels", "bucharest", "budapest", "buenos cires", "barcelona", "bilbao", "bologna", "bari", "bremen", "bordeaux", "bursa",
    "cologne", "cairo", "canberra", "caracas", "cardiff", "castries", "chisinau", "colombo", "conakry", "copenhagen", "cordoba", "catania", "chicago", "chelyabinsk",
    "dakar", "damascus", "dhaka", "dili", "djibouti", "dodoma", "doha", "dublin", "dushanbe", "dallas", "dusseldorf", "dortmund", "diyarbakir",
    "edinburgh", "essen",
    "freetown", "funafuti", "florence", "frankfurt", "frankfurt",
    "gaborone", "georgetown", "gitega", "guatemala city", "gyumri", "gavarr", "genoa",
    "hanoi", "harare", "havana", "helsinki", "honiara", "hrazdan", "hamburg", "hiroshima",
    "islamabad",
    "jakarta", "jerusalem", "juba",
    "kabul", "kampala", "kathmandu", "khartoum", "kiev", "kigali", "kingston", "kingstown", "kinshasa", "kuala lumpur", "kuwait", "kapan", "kazan",
    "lille", "lyon", "los Angeles", "la paz", "libreville", "lilongwe", "lima", "lisbon", "ljubljana", "lome", "london", "luanda", "lusaka", "luxembourg",
    "milan", "murcia", "madrid", "munich", "marseille", "montpellier", "madrid", "majuro", "malabo", "male", "managua", "manama", "manila", "maputo", "maseru", "mbabana", "melekeok", "mexico", "minsk", "mogadishu", "monaco", "monrovia", "montevideo", "moroni", "moscow", "muscat",
    "naples", "nagasaki", "new york", "nice", "nantes", "n'djamena", "nairobi", "nassau", "nay pyi taw", "new delhi", "niamey", "nicosia", "no official capital", "nouakchott", "nuku'alofa", "nur-sultan", "novosibirsk", "nizhny novgorod",
    "oslo", "ottawa", "ouagadougou", "omsk",
    "palermo", "palma", "phoenix", "philadelphia", "palikir", "panama", "paramaribo", "paris", "phnom penh", "podgorica", "port au prince", "port Louis", "port moresby", "port of spain", "port vila", "porto novo", "prague", "praia", "pretoria", "pristina", "pyongyang",
    "quito",
    "rabat", "reykjavik", "riga", "riyadh", "rome", "roseau", "rostov",
    "stuttgart", "seville", "saint george's", "strasbourg", "saint john's", "san jose", "san marino", "san salvador", "sana'a", "santiago", "santo domingo", "sao tome", "sarajevo", "seoul", "singapore", "skopje", "sofia", "stockholm", "suva", "stepanavan", "st. petersburg", "samara", "san jose", "san diego", "san antonio",
    "turin", "taipei", "toulouse", "tallinn", "tarawa atoll", "tashkent", "tbilisi", "tegucigalpa", "tehran", "thimphu", "tirana", "tokyo", "tripoli", "tunis",
    "ulaanbaatar",
    "vaduz", "verona", "valletta", "vatican", "victoria", "valencia", "vienna", "vientiane", "vilnius", "vanadzor", "vagharshapat",
    "warsaw", "washington", "wellington", "windhoek",
    "yamoussoukro", "yaounde", "yerevan","erevan", "yekaterinburg", "yeghegnadzor",
    "zagreb", "zaragoza",'Hvastovichi','Igarka','Iglino','Igra','Igrim','Iki-Burul','Iksha','Ilansky','Ilino','Ilino ','Ilskiy','Ilyinskoe ','Ilyinsky','Imeni Babushkina','imeni Morozova','Injutino','Inkerman','Innopolis','Inta','Inza','Inzer','Ipatovo','Irbit','Irkutsk','Isakly','Isetskoye','Isheevka','Ishim','Ishimbay','Isilkul','Iskitim','Istra','Istra ','Ivangorod','Ivanovo','Ivanteevka','Ivdel','Izberbash','Izborsk','Izhevsk','Izhmorsky',
]